"""Tests for GitLabClient — exclusions, generated file detection, diff parsing, formatting."""

from typing import cast

from app.claude import Finding
from app.constants import Severity
from app.gitlab import GitLabClient
from app.gitlab.models import MRChangesData


def _make_client(excluded_dirs: list[str] | None = None) -> GitLabClient:
    """Create a GitLabClient with a fake token for unit testing."""
    return GitLabClient(
        base_url="https://gitlab.example.com",
        token="fake-token",
        excluded_dirs=excluded_dirs,
    )


# ── _is_excluded() ──────────────────────────────────────────────


class TestIsExcluded:
    def test_excluded_top_level(self):
        client = _make_client(["node_modules"])
        assert client.is_excluded("node_modules/package/index.js") is True

    def test_not_excluded(self):
        client = _make_client(["node_modules"])
        assert client.is_excluded("src/main.py") is False

    def test_dotslash_normalization(self):
        client = _make_client(["./vendor"])
        assert client.is_excluded("vendor/lib.py") is True

    def test_nested_path(self):
        client = _make_client(["vendor"])
        assert client.is_excluded("src/vendor/lib.py") is True

    def test_partial_name_not_excluded(self):
        """'vendor' should not exclude 'vendoring/...'."""
        client = _make_client(["vendor"])
        assert client.is_excluded("vendoring/setup.py") is False

    def test_empty_excluded_dirs(self):
        client = _make_client([])
        assert client.is_excluded("anything/file.py") is False

    def test_multiple_excluded_dirs(self):
        client = _make_client(["node_modules", "dist", ".cache"])
        assert client.is_excluded("node_modules/pkg/x.js") is True
        assert client.is_excluded("dist/bundle.js") is True
        assert client.is_excluded(".cache/data.bin") is True
        assert client.is_excluded("src/app.py") is False


# ── _is_generated() ─────────────────────────────────────────────


class TestIsGenerated:
    def test_generated_by_marker(self):
        client = _make_client()
        diff = "@@ -0,0 +1,5 @@\n+// @generated by protobuf\n+message Foo {}\n"
        assert client.is_generated(diff) is True

    def test_do_not_edit_marker(self):
        client = _make_client()
        diff = "@@ -0,0 +1,3 @@\n+# DO NOT EDIT\n+x = 1\n"
        assert client.is_generated(diff) is True

    def test_openapi_generator(self):
        client = _make_client()
        diff = "+// Code generated by OpenAPI Generator\n+class Api {}\n"
        assert client.is_generated(diff) is True

    def test_normal_diff(self):
        client = _make_client()
        diff = "@@ -1,3 +1,4 @@\n def foo():\n+    print('hello')\n     return 42\n"
        assert client.is_generated(diff) is False

    def test_marker_deep_in_file_not_detected(self):
        """Markers beyond first ~20 lines should not trigger detection."""
        client = _make_client()
        lines = ["+" + f"line {i}" for i in range(25)]
        lines[22] = "+# @generated by tool"
        diff = "\n".join(lines)
        assert client.is_generated(diff) is False


# ── _parse_diff_position() ──────────────────────────────────────


class TestParseDiffPosition:
    BASE_SHA = "aaa"
    HEAD_SHA = "bbb"
    START_SHA = "ccc"

    def test_finds_added_line(self):
        client = _make_client()
        diff = "@@ -1,3 +10,4 @@\n context\n+added line\n context\n"
        pos = client._parse_diff_position(
            diff,
            target_line=11,
            old_path="old.py",
            new_path="new.py",
            base_sha=self.BASE_SHA,
            head_sha=self.HEAD_SHA,
            start_sha=self.START_SHA,
        )
        assert pos is not None
        assert pos["new_line"] == 11
        assert pos["new_path"] == "new.py"
        assert pos["position_type"] == "text"

    def test_returns_none_for_missing_line(self):
        client = _make_client()
        diff = "@@ -1,3 +1,3 @@\n context\n+added\n context\n"
        pos = client._parse_diff_position(
            diff,
            target_line=999,
            old_path="a.py",
            new_path="a.py",
            base_sha=self.BASE_SHA,
            head_sha=self.HEAD_SHA,
            start_sha=self.START_SHA,
        )
        assert pos is None

    def test_empty_diff(self):
        client = _make_client()
        pos = client._parse_diff_position(
            "",
            target_line=1,
            old_path="a.py",
            new_path="a.py",
            base_sha=self.BASE_SHA,
            head_sha=self.HEAD_SHA,
            start_sha=self.START_SHA,
        )
        assert pos is None

    def test_context_lines_count(self):
        """Context lines (no +/-) should advance the new-line counter."""
        client = _make_client()
        diff = "@@ -1,5 +1,6 @@\n line1\n line2\n line3\n+new_line\n line4\n"
        pos = client._parse_diff_position(
            diff,
            target_line=4,
            old_path="f.py",
            new_path="f.py",
            base_sha=self.BASE_SHA,
            head_sha=self.HEAD_SHA,
            start_sha=self.START_SHA,
        )
        assert pos is not None
        assert pos["new_line"] == 4


# ── format_merge_request_diff() ─────────────────────────────────


class TestFormatMergeRequestDiff:
    def test_excluded_files_filtered(self):
        client = _make_client(["vendor"])
        changes_data = cast(
            MRChangesData,
            {
                "changes": [
                    {"old_path": "vendor/lib.py", "new_path": "vendor/lib.py", "diff": "+x=1"},
                    {"old_path": "src/main.py", "new_path": "src/main.py", "diff": "+y=2"},
                ]
            },
        )
        result = client.format_merge_request_diff(changes_data)
        assert "vendor/lib.py" not in result
        assert "src/main.py" in result

    def test_generated_files_filtered(self):
        client = _make_client()
        changes_data = cast(
            MRChangesData,
            {
                "changes": [
                    {"old_path": "gen.py", "new_path": "gen.py", "diff": "# @generated by tool\n+x=1"},
                    {"old_path": "real.py", "new_path": "real.py", "diff": "+y=2"},
                ]
            },
        )
        result = client.format_merge_request_diff(changes_data)
        assert "gen.py" not in result
        assert "real.py" in result

    def test_empty_changes(self):
        client = _make_client()
        result = client.format_merge_request_diff({"changes": []})
        assert result == ""


# ── build_position_for_issue() ──────────────────────────────────


class TestBuildPositionForIssue:
    def test_returns_position_for_matching_file(self):
        client = _make_client()
        changes_data = cast(
            MRChangesData,
            {
                "diff_refs": {"base_sha": "aaa", "head_sha": "bbb", "start_sha": "ccc"},
                "changes": [
                    {
                        "old_path": "app.py",
                        "new_path": "app.py",
                        "diff": "@@ -1,2 +1,3 @@\n context\n+new_line\n",
                    }
                ],
            },
        )
        finding = Finding(
            file="app.py",
            line=2,
            severity=Severity.HIGH,
            category="test",
            description="d",
            exploit_scenario="e",
            recommendation="r",
            confidence=0.9,
        )
        pos = client.build_position_for_issue(changes_data, finding)
        assert pos is not None
        assert pos["new_line"] == 2

    def test_returns_none_for_unknown_file(self):
        client = _make_client()
        changes_data = cast(
            MRChangesData,
            {
                "diff_refs": {"base_sha": "a", "head_sha": "b", "start_sha": "c"},
                "changes": [],
            },
        )
        finding = Finding(
            file="unknown.py",
            line=1,
            severity=Severity.HIGH,
            category="test",
            description="d",
            exploit_scenario="e",
            recommendation="r",
            confidence=0.9,
        )
        assert client.build_position_for_issue(changes_data, finding) is None

    def test_returns_none_when_no_line(self):
        client = _make_client()
        changes_data = cast(
            MRChangesData,
            {
                "diff_refs": {"base_sha": "a", "head_sha": "b", "start_sha": "c"},
                "changes": [{"old_path": "a.py", "new_path": "a.py", "diff": "+x"}],
            },
        )
        finding = Finding(
            file="a.py",
            line=0,
            severity=Severity.HIGH,
            category="test",
            description="d",
            exploit_scenario="e",
            recommendation="r",
            confidence=0.9,
        )
        assert client.build_position_for_issue(changes_data, finding) is None
