"""Application constants."""

from enum import IntEnum, StrEnum


class ExitCode(IntEnum):
    """Application exit codes.

    Follows standard conventions:
    - 0: Success
    - 1: General errors
    - 2: Misconfiguration/invalid input
    """

    SUCCESS = 0
    GENERAL_ERROR = 1
    CONFIGURATION_ERROR = 2


class Severity(StrEnum):
    """Severity levels for security findings."""

    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


REVIEW_HEADER = "## 🤖 Code Review"

SEVERITY_ICONS = {
    Severity.HIGH: "🔴",
    Severity.MEDIUM: "🟠",
    Severity.LOW: "🟡",
}

GENERATED_MARKERS = (
    "@generated by",
    "@generated",
    "Code generated by OpenAPI Generator",
    "Code generated by protoc-gen-go",
    "AUTO-GENERATED FILE",
    "DO NOT EDIT",
)

MAX_PROMPT_SIZE_BYTES = 1024 * 1024  # 1MB

# The agent sometimes submits a valid result, the tool accepts it, and the session still
# refuses to finish: a stop hook demands another StructuredOutput call and the loop burns
# every remaining turn re-submitting the same payload. Stop once it is clearly looping.
MAX_STRUCTURED_OUTPUT_SUBMITS = 3

CONTEXT_OVERFLOW_PHRASES = (
    "prompt is too long",
    "prompt too long",
    "exceeds the available context size",
    "exceeds context size",
)
